name: dalkey_data
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0-271.7.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.5
  flutter_phone_direct_caller: ^2.1.1


  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.0+2
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.10.0"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/playstore.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/images/playstore.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/playstore.png"
    icon_size: 48 

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/